apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "enterprisecore.fullname" . }}-config
  labels:
    {{- include "enterprisecore.labels" . | nindent 4 }}
data:
  APP_ENV: "production"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8765"
  BACKEND_PORT: "8765"
  LOG_FORMAT: "json"
  DB_BACKEND: "postgres"
  ENTERPRISECORE_DATA_DIR: "/data"
  {{- if .Values.ollama.enabled }}
  OLLAMA_HOST: "http://{{ include "enterprisecore.ollama.fullname" . }}:11434"
  {{- end }}
  {{- if .Values.ingress.enabled }}
  CORS_ORIGINS: {{ printf "https://%s" .Values.ingress.host | quote }}
  {{- end }}
