{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "enterprisecore.backend.fullname" . }}
  labels:
    {{- include "enterprisecore.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "enterprisecore.backend.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "enterprisecore.frontend.fullname" . }}
  labels:
    {{- include "enterprisecore.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "enterprisecore.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
